categories:
  handlebars_forms:
    label: Handlebars Forms
  handlebars_forms.view:
    label: View
    parent: handlebars_forms

settings:
  plugin.tx_handlebarsforms.form.view.templateName:
    label: Default form template name
    type: string
    default: 'Form'
    category: handlebars_forms.view
