categories:
  hbs:
    label: Handlebars
  hbs.form:
    label: Handlebars form rendering
    parent: hbs

settings:
  plugin.tx_handlebars.form.view.templateName:
    label: Default form template name
    type: string
    default: 'Form'
    category: hbs.form
